### ISSUE TITLE
Breakdown schets - Responsive Design

### ISSUE THREAD

**Issue by osaoni** [osaoni/your-tribe-squad-page#1]
![Responsive Design-Breakdown Schets](https://github.com/user-attachments/assets/a9aea1f5-d483-4e94-a6c3-d552243521fb)

Dit is onze breakdown schets. We hebben onze een mobiele versie en een browser versie getekend. De breakpoint van onze Squadpage is op 720px. Zodra het scherm kleiner dan 720px is, worden de fotos onderbroken en dan komen ze onder elkaar te staan.

**Comment by Ravirkt** [comment]
/Users/ravitjikhoeri/Documents/GitHub/your-tribe-squad-page/ideation/wireframes/Wireframe Squadpage Info.png/Users/ravitjikhoeri/Documents/GitHub/your-tribe-squad-page/ideation/wireframes/Wireframe Squadpage.png

**Comment by Ravirkt** [comment]
![Wireframe Squadpage Info](https://github.com/user-attachments/assets/995981ee-9e38-4160-bf68-095081d5ee0c)
![Wireframe Squadpage Info](https://github.com/user-attachments/assets/995981ee-9e38-4160-bf68-095081d5ee0c)

**Comment by KoopReynders** [comment]
Per klus, of taak kun je een issue aanmaken waarin je schetsen, breakdown schets, ontwerpen in Figma, feedback en code verzameld. Als je een taak af hebt, sluit je het issue met een link naar de betreffende commit. Dat is gestructureerd werken ...
