### ISSUE TITLE
README.MD Maken

### ISSUE THREAD

**Issue by cedrikstephen** [osaoni/your-tribe-squad-page#7]
Met gedetailleerde beschrijving van ontwerpkeuzes

**Comment by Ravirkt** [comment]
https://github.com/osaoni/your-tribe-squad-page?tab=readme-ov-file

Feedback: foto toevoegen bovenaan de beschrijving, zodat iedereen gelijk de pagina kan zien
Feedback 2: Noteren welke technieken we hebben gebruikt

**Comment by Ravirkt** [comment]
Feedback is toegepast
